<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KKIOJ2D" ignored="0" name="ChromeTest" tests="3" failures="1" timestamp="03 Mar 2021 04:51:52 GMT" time="75.537" errors="0">
  <testcase name="VerifyRefiSavings" time="19.577" classname="com.tictoc.testcases.VerifySavingsDDTonGrid"/>
  <testcase name="VerifyRefiSavings" time="19.093" classname="com.tictoc.testcases.VerifySavingsDDTonGrid"/>
  <testcase name="VerifyRefiSavings" time="63.068" classname="com.tictoc.testcases.VerifySavingsDDTonGrid">
    <failure type="java.lang.AssertionError" message="Set test result to FAIL due to failed steps">
      <![CDATA[java.lang.AssertionError: Set test result to FAIL due to failed steps
at utilities.auto.TestNGListener.onTestSuccess(TestNGListener.java:55)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- VerifyRefiSavings -->
</testsuite> <!-- ChromeTest -->
