<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KKIOJ2D" ignored="0" name="EdgeTest" tests="1" failures="1" timestamp="14 Mar 2021 03:55:38 GMT" time="35.518" errors="0">
  <testcase name="verifyHPPricing" time="26.571" classname="co.happy.testcases.PricingValidation">
    <failure type="java.lang.AssertionError" message="Set test result to FAIL due to failed steps">
      <![CDATA[java.lang.AssertionError: Set test result to FAIL due to failed steps
at utilities.auto.TestNGListener.onTestSuccess(TestNGListener.java:55)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyHPPricing -->
</testsuite> <!-- EdgeTest -->
